name: sendEmail

on:
 push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send mailer
    - uses: shipravalecha/github-action-maven-example-start/send-mail@2.299.1
    - uses: actions/checkout@v2
    - name: Send email
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        account: ${{ secrets.ACCOUNT }}
        password: ${{ secrets.MAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: shipravalecha92@gmail.com,khanriha9851@gmail.com
        # from email name
        from: ${{secrets.MAIL_ADDRESS}}
